### ISSUE TITLE
Can't read source file, when I use a target

### ISSUE THREAD

**Issue by Thomas-P** [chrisprice/grunt-rollup#12]
Hello,

when I use a target, rollup did not convert by sending the error message:

```
Warning: Unable to write "src" file (Error code: EISDIR). Use --force to continue.
```

This did not work

``` Javascript
rollup: {
            build: {
                options: {
                    format: 'cjs',
                    sourceMap: true,
                },
                files: {
                    'dest': 'dest.js',
                    'src': 'source.js',
                },
            },
        }
```

This  work

``` Javascript
rollup: {
                options: {
                    format: 'cjs',
                    sourceMap: true,
                },
                files: {
                    'dest': 'dest.js',
                    'src': 'source.js',
                },
        }
```

**Comment by ulrik59** [comment]
Same problem here, I wanted to differenciate "dev" and "prod" build as the last one is minified, but I can't...

**Comment by chrisprice** [comment]
I think this might just be a syntax problem, have you tried the following?

```Javascript
rollup: {
    build: {
        options: {
            format: 'cjs',
            sourceMap: true,
        },
        files: [{ // <-- N.B. array
            'dest': 'dest.js',
            'src': 'source.js',
        }],
    },
}
```

**Comment by Thomas-P** [comment]
I could not test it in fact of using another build management. But would it possible, to change the interface, for a better handling?

**Comment by chrisprice** [comment]
To be honest I'm not sure why it doesn't work without the square braces.
Our code doesn't really have anything to do with that,we rely on grunt for
that I think.

**Comment by halfnibble** [comment]
Interesting. I can confirm the issue, and the resolution.

None of my other grunt packages work this way. But, does this allow one to have multiple "rollups" since we can only specify a single `src` per object? That would be a neat feature.

**Comment by GMartigny** [comment]
Hi,
Can anyone confirm this is still an issue ?
Since last comment, grunt and rollup have been updated and I cannot reproduce this issue.

**Comment by GMartigny** [comment]
Any update on this ?

**Comment by GMartigny** [comment]
I'm closing this issue since it's not reproductible anymore. You can still open another issue if this surface again.
