### ISSUE TITLE
Fails with es2015 or es2015-rollup

### ISSUE THREAD

**Issue by FezVrasta** [chrisprice/grunt-rollup#18]
I have tried to use both `es2015` and `es2015-rollup` presets on my project but both fails.  
This is the output when I use `es2015-rollup` (and even if I use just `es2015`):

> Warning: Error transforming ~/src/popper.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information Use --force to continue.

If I specify plugins manually it works.

https://github.com/FezVrasta/popper.js/blob/v1-dev/Gruntfile.js

How can I fix the problem?

**Comment by FezVrasta** [comment]
Seems like it works if I use `es2015-loose-rollup`, is it expected?

**Comment by zeitiger** [comment]
@FezVrasta you need to update to `.babelrc` file and anything should go fine 😄

**Comment by FezVrasta** [comment]
Thanks, actually I get this stuff if I try your configuration:

```
Warning: Error transforming /Users/federicozivolo/Progetti/popper-js/src/popper.js with 'babel' plugin: [BABEL] /Users/federicozivolo/Progetti/popper-js/src/x.js: Using removed Babel 5 option: foreign.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules Use --force to continue.
```

**Comment by FezVrasta** [comment]
Ah! Great!
