### ISSUE TITLE
options.extend not supported

### ISSUE THREAD

**Issue by leeyeh** [chrisprice/grunt-rollup#31]
New options like `extend` and `amd` are not passed to `bundle.generate()`.

There might be more options in the future. Will it be more convenient to filter `rollup.rollup()` options and pass the rest to `bundle.generate()`?

**Comment by reppners** [comment]
Running into the same issue, it would be cool if options handling could be refactored to pass through the options whenever possible so the plugin does not have to change if the options api of rollup changes.

**Comment by GMartigny** [comment]
This is fixed by the [v10.0.0](https://github.com/chrisprice/grunt-rollup/releases/tag/v10.0.0) release. :tada:
