### ISSUE TITLE
Specify rollup as a peer dependency to allow users to override it

### ISSUE THREAD

**Issue by ghost** [chrisprice/grunt-rollup#43]
The latest version of rollup is incompatible with the version required by `grunt-rollup`. Since this repo is not very active, it's probably best if the user provides the rollup version required (as a peer dependency) instead of having to update every time rollup updates.

**Comment by rnavaneethan** [comment]
Any plan on fixing this? grunt-rollup-commonjs plugin updated to use latest rollup version. When we use it's upgraded version in conjunction with grunt-rollup, build is faining. Please refer [commonjs issue](https://github.com/rollup/rollup-plugin-commonjs/pull/287#issuecomment-370615694)

**Comment by chrisprice** [comment]
I'm no longer able to maintain this repository, if anyone would like to take over please let me know.

**Comment by GMartigny** [comment]
This is fixed by the [v10.0.0](https://github.com/chrisprice/grunt-rollup/releases/tag/v10.0.0) release. :tada:
