### ISSUE TITLE
Feature: option 'cwd'

### ISSUE THREAD

**Issue by db-developer** [chrisprice/grunt-rollup#44]
Would it be possible to have an option 'cwd' which is not passed to rollup but is instead used to do a `grunt.file.setBase( cwd )` before starting rollup?

Reason:
While tsc accepts a "basedir",  rollup won't.
Having a build directory where all files to build are gathered by  grunt, will then require a tsconfig.json for tsc in the build directory and one for rollup, in the directory where gruntfile.js resides...
If grunt-rollup did a cwd, there would be no need for a second tsconfig.json or a rollup-module-id-resolver-plugin.

**Comment by GMartigny** [comment]
I'm not sure to understand why you need to have a `tsconfig.json` at 2 places. Could you show an example of your issue in a live repo ?

**Comment by GMartigny** [comment]
Any update on this ?

**Comment by db-developer** [comment]
No. Already forked and changed on my own. Thanx.
Feel free to close. Nevermind.
