### ISSUE TITLE
Example of multiple bundle configuration

### ISSUE THREAD

**Issue by smfukaya** [chrisprice/grunt-rollup#64]
Hi

Could you please update the README.md with a multiple bundle (iife and umd) configuration?

#### Information
 - Your current node version: v11.9.0
 - The package version you used: v1.3.0

#### Description
I need to create two bundles (iife and umd).

```
rollup: {
      options: {
        treeshake: true,

        onwarn: function (warning) {
          // Skip certain warnings
          console.warn('"' + warning.code + '": ' + warning.message);
          if (warning.code === 'THIS_IS_UNDEFINED') { return; }
          // console.warn everything else
        },
        plugins: [
          commonjs({}),
          swag.nodeResolve({
            basedir: __dirname,
            prefixes: {}
          }),
          swag.remapImports(),
          RollupPostcss({
            plugins: [
              autoprefixer(),
            ]
          }),
        ]
      },
      plugin: {
        options: {
          format: 'iife',
        },
        files: [
          {
            src: libPluginPath,
            dest: scratchPluginPath
          }
        ]
      },
      iframe: {
        options: {
          format: 'umd',
        },
        files: [
          {
            src: libIframePath,
            dest: scratchPluginPath
          },
        ]
      }
    },
```

**Comment by GMartigny** [comment]
Hi,

I guess the example you provided works as expected.

Using multiple source file is a Grunt configuration specification. You can use a [variety of formats](https://gruntjs.com/configuring-tasks#compact-format) to specify your input and output files.

**Comment by gerhard-lechner** [comment]
Hi,

is there a way to define the `name` option dynamically? My config looks like this:

```
rollup: {
  multiple: {
    options: { format: 'iife', name: 'script' },
    files: [{
      expand: true,
      cwd: '/path/to/files',
      src: ['*.js'],
      dest: '/path/to/output',
    }]
  }
}
```

So the goal here is to process a couple of files, each file on his own and receive multiple output files. However, each file uses the name `script` which causes a collision if I ever want to use two files on the same page. I'd rather have the name set dynamically, e.g. within a function that creates the name based on the input file name or similar.

Is there any chance of getting this to work without having to declare a single grunt task for each file?

**Comment by GMartigny** [comment]
Grunt configuration allow you to do so. Please read the documentation to know every possibilities. 
https://gruntjs.com/configuring-tasks#building-the-files-object-dynamically
